server {
    listen 80;
    server_name _;

    # Archivos de prosodia (raíz)
    location / {
        root /usr/share/nginx/html;
        autoindex on;
    }

    # Archivos de TalkIA en /talkia/
    location /talkia/ {
        alias /talkia-releases/;
        autoindex on;
    }

    # Acceso directo al APK de TalkIA
    location /talkia-latest.apk {
        alias /talkia-releases/talkia-latest.apk;
    }
    location /talkia-prev.apk {
        alias /talkia-releases/talkia-prev.apk;
    }
}
